### ISSUE TITLE
Can you catch pvk?

### ISSUE THREAD

**Issue by mfournial** [CrynetLogistics/raytrace#3]

**Comment by PK398** [comment]
@CrynetLogistics I am uncatchable. I am a legendary Pokemon.

**Comment by CrynetLogistics** [comment]
I disagree. Catch-able with a slight exertion of effort.
Go catch your pvks, I think this is resolved. Reopen if people still cannot catch it.

**Comment by PK398** [comment]
@CrynetLogistics I've been walking for hours on Pokemon go and I have yet to catch a pvk. Any Tips?
